- name: Deploy mysql Docker master
  hosts: mysql_master
  become: true
  roles:
    - role: mysql_master

- name: Deploy mysql Docker slave-1
  hosts: mysql_slave_1
  become: true
  roles:
    - role: mysql_slave_1

- name: Deploy mysql Docker slave-2
  hosts: mysql_slave_2
  become: true
  roles:
    - role: mysql_slave_2
